### PR TITLE
Fix deprecation loop

### PR DESCRIPTION
**Pull request by goretkin**

### CODE REVIEW

**Comment by andreasnoack** [comment]
Would you mind adjusting `.travis.yml` to enable testing 0.6 as part of this PR?

**Comment by goretkin** [comment]
Like that?

**Comment by andreasnoack** [comment]
Exactly. Now we'll know if things work on 0.6.

**Comment by goretkin** [comment]
On Julia 0.5.3 and ArrayViews 0.6.4
`@which ArrayViews.contrank(:,:,:)` points to https://github.com/JuliaArrays/ArrayViews.jl/blob/715d637fbdd0f6dca6a03d1f2d7c8d248b4abde8/src/contrank.jl#L54

**Comment by goretkin** [comment]
(fixed in #56)

**Comment by goretkin** [comment]
Closed in favor of https://github.com/JuliaArrays/ArrayViews.jl/pull/59

**Pull request closed without merging**
